### ISSUE TITLE
Compilation of linenoise

### ISSUE THREAD

**Issue by BlackEdder** [D-Programming-Deimos/linenoise#2]
I was wondering how to exactly use this library from D. I tried to compile the example (dub -c example), but it gives the following error: 
linenoise: ["linenoise"]
Building linenoise configuration "example", build type debug.
Compiling...
Linking...
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.1/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -llinenoise
collect2: error: ld returned 1 exit status
--- errorlevel 1
FAIL .dub/build/example-debug-linux.posix-x86_64-dmd-77D4FDD7005466EA2A286ACED0C0226D linenoise executable
Error executing command run: Link command failed with exit code 1

When calling dub -c lib I get:
Error executing command run: Main package must have a binary target type, not sourceLibrary. Cannot build.

Do I have to build the c version of linenoise as a shared library and install it in the appropriate directories?

(I am on linux)

**Comment by BlackEdder** [comment]
I figured out that I needed to turn linenoise.c into a static library and put it under /usr/lib. After that compilation of the example worked fine. 

(Sorry for the noise) Closing it.

**Comment by logicfish** [comment]
On windows to make linenoise.lib I used cmake, visual studio and the c files from here https://github.com/arangodb/linenoise-ng
I had to use the release build or I got an undefined symbol from the linker.
